### ISSUE TITLE
KNOWN BUGS

### ISSUE THREAD

**Issue by EwwItsMike** [EwwItsMike/CCClogSpamHider#1]
A list of known bugs, to be fixed in a later date.

Currently known bugs:
- Amulet of Defence (t) still shows up with Beginner clue rewards filtered

Fixed bugs:
- Code did not isolate the item from the message, causing bugs when checking if the messages matches exactly.
- Ancient page still showed up with My Notes filtered (see previous)
- Bucket helm still showed up with Elite clue rewards filtered (see previous)
- Bandos chaps still showed up with Hard clue rewards filtered
- Ancient stole still showed up with Medium clue rewards filtered
- Cavaliers still showed up with Hard clue rewards filtered

**Comment by EwwItsMike** [comment]
2024-05-02 10:19:33 CEST [Client] WARN  n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.StringIndexOutOfBoundsException: begin 0, end 62, length 24
	at java.base/java.lang.String.checkBoundsBeginEnd(Unknown Source)
	at java.base/java.lang.String.substring(Unknown Source)
	at com.example.CCClogSpamHiderPlugin.extractItemFromMessage(CCClogSpamHiderPlugin.java:186)
	at com.example.CCClogSpamHiderPlugin.onScriptCallbackEvent(CCClogSpamHiderPlugin.java:166)
	at net.runelite.client.eventbus.EventBus$Subscriber.invoke(EventBus.java:70)
	at net.runelite.client.eventbus.EventBus.post(EventBus.java:223)
	at net.runelite.client.callback.Hooks.post(Hooks.java:204)
	at client.si(client.java:55642)
	at el.af(el.java:59594)
	at fn.ah(fn.java:65268)
	at kl.az(kl.java:108)
	at client.hu(client.java:3476)
	at client.bh(client.java:1167)
	at bx.aa(bx.java:380)
	at bx.ma(bx.java)
	at bx.run(bx.java:55124)
	at java.base/java.lang.Thread.run(Unknown Source)
